name: multi_network_image
description: "A package that allows you to handle adaptive images with ease."
version: 0.0.1
homepage: "https://nikodembernat.com"
repository: "https://github.com/n-bernat/flutter_multi_network_image"
issue_tracker: "https://github.com/n-bernat/flutter_multi_network_image/issues"

topics:
  - flutter
  - image
  - network-image

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

dependencies:
  collection: ^1.19.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  leancode_lint: ^15.0.0
